const inlineKeyboardKH = require('../constant/inline_keyboard_kh');
const inlineKeyboardEN = require('../constant/inline_keyboard_en');

exports.inline_keyboard = {
    lang_kh: {
        languageSelection: inlineKeyboardEN.languageSelection,
        userGenderAnswer: inlineKeyboardKH.user_gender_answer_button,
        mainMenu: inlineKeyboardKH.main_menu_option_kh,
        productOption: inlineKeyboardKH.product_option_button_kh,
        shortSavingsProduct: inlineKeyboardKH.product_short_savings_option_kh,
        backToMainMenu: inlineKeyboardKH.main_menu_button_option_kh,
        qap_question_start: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_start,
        qap_question_completed: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_completed,
        qap_question_1: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_1,
        qap_question_2: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_2,
        qap_question_3: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_3,
        qap_question_4: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_4,
        qap_question_5: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_5,
        qap_question_6: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_6,
        qap_question_7: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_7,
        qap_question_8: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_8,
        qap_question_9: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_9,
        qap_question_10: inlineKeyboardKH.multiple_choice_answers_kh.qap_question_10,
        talk_to_agent: inlineKeyboardKH.live_chat_agent_response_kh,
        agent_main_option_button: inlineKeyboardKH.agent_main_option_button_kh,
        agent_customer_list_option_button: inlineKeyboardKH.agent_customer_list_option_button_kh,
    },
    lang_en: {
        languageSelection: inlineKeyboardEN.language_selection,
        userGenderAnswer: inlineKeyboardEN.user_gender_answer_button,
        mainMenu: inlineKeyboardEN.main_menu_option_en,
        productOption: inlineKeyboardEN.product_option_button_en,
        shortSavingsProduct: inlineKeyboardEN.product_short_savings_option_en,
        backToMainMenu: inlineKeyboardEN.main_menu_button_option_en,
        qap_question_start: inlineKeyboardEN.multiple_choice_answers_en.qap_question_start,
        qap_question_completed: inlineKeyboardEN.multiple_choice_answers_en.qap_question_completed,
        qap_question_1: inlineKeyboardEN.multiple_choice_answers_en.qap_question_1,
        qap_question_2: inlineKeyboardEN.multiple_choice_answers_en.qap_question_2,
        qap_question_3: inlineKeyboardEN.multiple_choice_answers_en.qap_question_3,
        qap_question_4: inlineKeyboardEN.multiple_choice_answers_en.qap_question_4,
        qap_question_5: inlineKeyboardEN.multiple_choice_answers_en.qap_question_5,
        qap_question_6: inlineKeyboardEN.multiple_choice_answers_en.qap_question_6,
        qap_question_7: inlineKeyboardEN.multiple_choice_answers_en.qap_question_7,
        qap_question_8: inlineKeyboardEN.multiple_choice_answers_en.qap_question_8,
        qap_question_9: inlineKeyboardEN.multiple_choice_answers_en.qap_question_9,
        qap_question_10: inlineKeyboardEN.multiple_choice_answers_en.qap_question_10,
        talk_to_agent: inlineKeyboardEN.talk_to_agent,
        agent_main_option_button: inlineKeyboardEN.agent_main_option_button_en,
        agent_customer_list_option_button: inlineKeyboardEN.agent_customer_list_option_button_en,
    }
}